# Generated by Django 5.2.7 on 2025-10-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file1_size', models.BigIntegerField(blank=True, null=True)),
                ('file2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file2_size', models.BigIntegerField(blank=True, null=True)),
                ('file3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file3_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
